### PR TITLE
Update Data.java

### PR DESCRIPTION
**Pull request by Olzie-12**

### CODE REVIEW

**Comment by ItsWagPvP** [comment]
why do you want to change OfflinePlayer instead of Player? the command is still using Player

**Comment by Olzie-12** [comment]
Oh i was just changing that for the vault api. i completely forgot about the command

**Review by ItsWagPvP — APPROVED** [review]
Ok thanks for the (PlayerAuctions) compatibility

**Comment by Olzie-12** [comment]
It's not just for my plugin, other plugins will also find it useful as then you can deposit money offline

**Pull request merged**
